-
  name: Apply for this opportunity multiquestion
  editable: True
  description:
    default: Buyers will use the information suppliers provide here to create a shortlist.
    digital-specialists: You can only offer 1 specialist for this opportunity. Buyers will use the information suppliers provide here to create a shortlist.
  questions:
    - respondToEmailAddress
    - niceToHaveRequirementsMultiquestion
